name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: dfdff
      id: dfdff
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: dfdff
        setup-command: ''
        command: python3.main.py
        input: ''
        expected-output: ''
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DFDFF_RESULTS: "${{steps.dfdff.outputs.result}}"
      with:
        runners: dfdff
